#!/bin/bash
set -e
source="$1"
output="$2"
if [ -z $source ]; then
    echo "usage: uasm <source>" >&2
    exit 1
fi

labels=$(basename $source ".asm").labels

cat $source | ./uasm1 > $labels
cat $source | ./uasm2 $labels $output
